-- PostgreSQL DDL Script for Sentiment Analysis Pipeline
-- Generated by Antigravity (modified to include password hashing for authentication compatibility)

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    user_id          SERIAL PRIMARY KEY,
    username         VARCHAR(100) NOT NULL UNIQUE,
    hashed_password  VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL UNIQUE,
    role             VARCHAR(50)  NOT NULL CHECK (role IN ('general', 'developer', 'admin')),
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Core Comments Table (Immutable Raw Scraped Data)
CREATE TABLE IF NOT EXISTS public.comments (
    comment_id          VARCHAR(100) PRIMARY KEY,
    comment_text        TEXT NOT NULL,
    source_url          VARCHAR(500) NOT NULL,
    created_at          TIMESTAMP,
    date_collected      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    collection_source   VARCHAR(100) NOT NULL,
    apify_dataset_id    VARCHAR(100),
    apify_run_id        VARCHAR(100)
);

-- 3. Preprocessed Comments Table (Text Cache)
CREATE TABLE IF NOT EXISTS public.preprocessed_comments (
    preprocessed_id  SERIAL PRIMARY KEY,
    comment_id       VARCHAR(100) NOT NULL UNIQUE,
    cleaned_text     TEXT NOT NULL,
    metadata         JSONB,
    preprocessed_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_preproc_comment FOREIGN KEY (comment_id)
        REFERENCES public.comments (comment_id) ON DELETE CASCADE
);

-- 4. Predictions Table (Model Output Cache)
CREATE TABLE IF NOT EXISTS public.predictions (
    prediction_id        SERIAL PRIMARY KEY,
    comment_id           VARCHAR(100) NOT NULL,
    predicted_label      VARCHAR(50) NOT NULL,
    predicted_confidence NUMERIC(10,8) NOT NULL,
    score_negative       NUMERIC(10,8) NOT NULL,
    score_neutral        NUMERIC(10,8) NOT NULL,
    score_positive       NUMERIC(10,8) NOT NULL,
    model_name           VARCHAR(100) NOT NULL,
    model_version        VARCHAR(50) NOT NULL,
    model_family         VARCHAR(50) NOT NULL,
    predicted_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pred_comment FOREIGN KEY (comment_id)
        REFERENCES public.comments (comment_id) ON DELETE CASCADE
);

-- 5. Developer Annotations Table (Optional Training Data)
CREATE TABLE IF NOT EXISTS public.dev_annotations (
    comment_id        VARCHAR(100) PRIMARY KEY,
    topic_label       VARCHAR(50),
    sentiment_label   VARCHAR(50),
    confidence        VARCHAR(20),
    include           BOOLEAN DEFAULT TRUE,
    notes             TEXT,
    annotated_by      VARCHAR(100),
    annotated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anno_comment FOREIGN KEY (comment_id)
        REFERENCES public.comments (comment_id) ON DELETE CASCADE
);

-- 6. Activity Logs Table (Audit Trail)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    log_id           SERIAL PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    comment_id       VARCHAR(100),
    action_type      VARCHAR(50) NOT NULL CHECK (action_type IN ('ingest', 'preprocess', 'predict', 'annotation_upload')),
    action_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    details          TEXT,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_log_comment FOREIGN KEY (comment_id)
        REFERENCES public.comments (comment_id) ON DELETE SET NULL
);

-- Indexes for fast joins
CREATE INDEX IF NOT EXISTS idx_predictions_comment_id ON public.predictions(comment_id);
CREATE INDEX IF NOT EXISTS idx_dev_annotations_comment_id ON public.dev_annotations(comment_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON public.activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_comment_id ON public.activity_logs(comment_id);
